/** DIGIMON NAMES */

const digimon_names = {
    "アバドモン": "Abbadomon",
    "アバドモンコア": "Abbadomon Core",
    "アキレウスモン": "Achillesmon",
    "アイギオテュースモン": "Aegiochusmon",
    "アイギオテュースモン：ブルー": "Aegiochusmon: Blue",
    "アイギオテュースモン：ダーク": "Aegiochusmon: Dark",
    "アイギオテュースモン：グリーン": "Aegiochusmon: Green",
    "アイギオテュースモン：ホーリー": "Aegiochusmon: Holy",
    "アイギオモン": "Aegiomon",
    "イージスドラモン": "Aegisdramon",
    "エクスドラモン": "Aequcedramon",
    "エアロブイドラモン": "Aero V-dramon",
    "アグニモン": "Agnimon",
    "アグモン": "Agumon",
    "アグモン（X抗体）": "Agumon (X-Antibody)",
    "アグモン（２００６アニメ版）": "Agumon (2006 Anime Version)",
    "アグモン（黒）": "Agumon (Black)",
    "アグモン（黒）（X抗体）": "Agumon (Black) (X-Antibody)",
    "アグモン（黒）（２００６アニメ版）": "Agumon (Black) (2006 Anime Version)",
    "アグモン -勇気の絆-": "Agumon -Yuki no Kizuna-",
    "アグモン バーストモード": "Agumon: Burst Mode",
    "アグモン博士": "Agumon Hakase",
    "空母ホエーモン": "Aircraft Carrier Whamon",
    "エアドラモン": "Airdramon",
    "アヤタラモン": "Ajatarmon",
    "アカトリモン": "Akatorimon",
    "アルダモン": "Aldamon",
    "アルゴモン（幼年期I）": "Algomon (Baby I)",
    "アルゴモン（幼年期II）": "Algomon (Baby II)",
    "アルゴモン（成長期）": "Algomon (Child)",
    "アルゴモン（成熟期）": "Algomon (Adult)",
    "アルゴモン（完全体）": "Algomon (Perfect)",
    "アルゴモン（究極体）": "Algomon (Ultimate)",
    "アロモン": "Allomon",
    "アロモン（X抗体）": "Allomon (X-Antibody)",
    "アルファモン": "Alphamon",
    "アルファモン：王竜剣": "Alphamon: Ouryuken",
    "アルラウモン": "Alraumon",
    "アマテラスモン": "Amaterasumon",
    "アモン": "Amon",
    "アンフィモン": "Amphimon",
    "エンシェントビートモン": "Ancient Beatmon",
    "エンシェントガルルモン": "Ancient Garurumon",
    "エンシェントグレイモン": "Ancient Greymon",
    "エンシェントイリスモン": "Ancient Irismon",
    "エンシェントメガテリウモン": "Ancient Megatheriumon",
    "エンシェントマーメイモン": "Ancient Mermaimon",
    "エンシェントスフィンクモン": "Ancient Sphinxmon",
    "エンシェントトロイアモン": "Ancient Troiamon",
    "エンシェントボルケーモン": "Ancient Volcamon",
    "エンシェントワイズモン": "Ancient Wisemon",
    "アンティラモン": "Andiramon",
    "アンティラモン（デーヴァ）": "Andiramon (Deva)",
    "アンドロモン": "Andromon",
    "エンジェモン": "Angemon",
    "エンジェウーモン": "Angewomon",
    "エンジェウーモン（X抗体）": "Angewomon (X-Antibody)",
    "アンゴラモン": "Angoramon",
    "暗黑女娲兽": "AnheiNüwashou",
    "アンキロモン": "Ankylomon",
    "アノマロカリモン": "Anomalocarimon",
    "アノマロカリモン（X抗体）": "Anomalocarimon (X-Antibody)",
    "アヌビモン": "Anubimon",
    "アポカリモン": "Apocalymon",
    "アポロモン": "Apollomon",
    "アポロモン：ウィスパード": "Apollomon: Whispered",
    "アポロモンダークネスモード": "Apollomon Darkness Mode",
    "アクィラモン": "Aquilamon",
    "アルボルモン": "Arbormon",
    "アーケロモン": "Archelomon",
    "アルケニモン": "Archnemon",
    "アルクトゥルスモン": "Arcturusmon",
    "アリエモン": "Ariemon",
    "アルカディモン幼年期": "Arkadimon Baby",
    "アルカディモン成長期": "Arkadimon Child",
    "アルカディモン成熟期": "Arkadimon Adult",
    "アルカディモン完全体": "Arkadimon Perfect",
    "アルカディモン究極体": "Arkadimon Ultimate",
    "アルカディモン超究極体": "Arkadimon Super Ultimate",
    "アルケーエンジェモン": "Arkhai Angemon",
    "アルマリザモン": "Arma Lizamon",
    "アルマジモン": "Armadimon",
    "アーマゲモン": "Armagemon",
    "アルマモン": "Armamon",
    "アルマモン：バーストモード": "Armamon: Burst Mode",
    "アレスタードラモン": "Arresterdramon",
    "アレスタードラモン：スペリオルモード": "Arresterdramon: Superior Mode",
    "アレスタードラモン：スペリオルモード": "Arresterdramon: Superior Mode (Brave Snatcher)",
    "アサルトモン": "Assaultmon",
    "アスタモン": "Astamon",
    "アシュラモン": "Asuramon",
    "アタマデカチモン": "Atamadekachimon",
    "アトラーバリスタモン": "Atlur Ballistamon",
    "アトラーカブテリモン（青）": "Atlur Kabuterimon (Blue)",
    "アトラーカブテリモン（赤）": "Atlur Kabuterimon (Red)",
    "アヴェンジキッドモン": "Avenge Kidmon",
    "アズダルモン": "Azhdarmon",
    "バアルモン": "Baalmon",
    "バアルモン（X抗体）": "Baalmon (X-Antibody)",
    "ババモン": "Babamon",
    "バブンガモン": "Baboongamon",
    "ベビドモン": "Babydmon",
    "バッカスモン": "Bacchusmon",
    "バコモン": "Bacomon",
    "バグラモン": "Bagramon",
    "バグラモン大天使形態": "Bagramon (Archangel Form)",
    "バイフーモン": "Baihumon",
    "バケモン": "Bakemon",
    "バクモン": "Bakumon",
    "バリバステモン": "Balli Bastemon",
    "バリスタモン": "Ballistamon",
    "バリスタモンＭＣ": "Ballistamon MC",
    "バリスタモンＳＲ": "Ballistamon SR",
    "バルキモン": "Baluchimon",
    "バンチョーゴーレモン": "Bancho Golemon",
    "バンチョーレオモン": "Bancho Leomon",
    "バンチョーレオモン バーストモード": "Bancho Leomon: Burst Mode",
    "バンチョーリリモン": "Bancho Lilimon",
    "バンチョーマメモン": "Bancho Mamemon",
    "バンチョースティングモン": "Bancho Stingmon",
    "バオハックモン": "Bao Hackmon",
    "バルバモン": "Barbamon",
    "バルバモン（X抗体）": "Barbamon (X-Antibody)",
    "バロモン": "Baromon",
    "バステモン": "Bastemon",
    "バッテリモン": "Batterimon",
    "戦闘武装トレイルモン": "Battle Armament Trailmon",
    "ベアモン": "Bearmon",
    "ベルスターモン": "Beel Starmon",
    "ベルスターモン（X抗体）": "Beel Starmon (X-Antibody)",
    "ベルゼブモン": "Beelzebumon",
    "ベルゼブモンブラストモード": "Beelzebumon: Blast Mode",
    "ベルゼブモン（X抗体）": "Beelzebumon (X-Antibody)",
    "ベルゼブモン": "Beelzebumon (2010 Anime Version)",
    "ベリアルヴァンデモン": "Belial Vamdemon",
    "ベルフェモンレイジモード": "Belphemon: Rage Mode",
    "ベルフェモンスリープモード": "Belphemon: Sleep Mode",
    "ベルフェモン（X抗体）": "Belphemon (X-Antibody)",
    "ベムモン": "BEMmon",
    "ベオウルフモン": "Beowolfmon",
    "暴走タイタモン": "Berserk Titamon",
    "ベソボムモン": "Beso Bombmon",
    "ベタモン": "Betamon",
    "ベタモン（X抗体）": "Betamon (X-Antibody)",
    "ベテルガンマモン": "Betel Gammamon",
    "ベツモン": "Betsumon",
    "ビビモン": "Bibimon",
    "ビッグマメモン": "Big Mamemon",
    "ビッグウッコモン": "Big Ukkomon",
    "バイオクアトルモン": "Bio Coatlmon",
    "バイオダークドラモン": "Bio Darkdramon",
    "バイオロトスモン": "Bio Lotusmon",
    "バイオスピノモン": "Bio Spinomon",
    "バイオステゴモン": "Bio Stegomon",
    "バイオサンダーバーモン": "Bio Thunderbirmon",
    "バードラモン": "Birdramon",
    "ビショップチェスモン（黒）": "Bishop Chessmon (Black)",
    "ビショップチェスモン（白）": "Bishop Chessmon (White)",
    "ビットモン": "Bitmon",
    "ブラックガルゴモン": "Black Galgomon",
    "ブラックガオガモン": "Black Gaogamon",
    "ブラックグラウモン": "Black Growmon",
    "ブラックギルモン": "Black Guilmon",
    "ブラックキングヌメモン": "Black King Numemon",
    "ブラックマッハガオガモン": "Black Mach Gaogamon",
    "ブラックメガログラウモン": "Black Megalo Growmon",
    "ブラックラピッドモン": "Black Rapidmon",
    "ブラックセントガルゴモン": "Black Saint Galgomon",
    "ロギモン": "Logimon",
    "ブートモン": "Bootmon",
    "ブラックセラフィモン": "Black Seraphimon",
    "ブラックセラフィモン": "Black Seraphimon (DW3)",
    "ブラックシャウトモンＸ７": "Black Shoutmon X7",
    "ブラックテイルモン": "Black Tailmon",
    "ブラックテイルモン Uver.": "Black Tailmon Uver.",
    "ブラックウォーグレイモン": "Black War Greymon",
    "ブラックウォーグレイモン（X抗体）": "Black War Greymon (X-Antibody)",
    "ブレイドクワガーモン": "Blade Kuwagamon",
    "ブラストモン": "Blastmon",
    "ブリキモン": "Blikmon",
    "ブリンプモン": "Blimpmon",
    "ブリッツグレイモン": "Blitz Greymon",
    "ブリッツモン": "Blitzmon",
    "ブリザーモン": "Blizzarmon",
    "ブルムロードモン": "Bloom Lordmon",
    "ブロッサモン": "Blossomon",
    "ブルコモン": "Blucomon",
    "ブルーメラモン": "Blue Meramon",
    "ボアモン": "Boarmon",
    "ボコモン": "Bokomon",
    "ボルグモン": "Bolgmon",
    "ボルトモン": "Boltmon",
    "ボンバーナニモン": "Bomber Nanimon",
    "ボマーモン": "Bombermon",
    "ボムモン": "Bombmon",
    "ボムモン": "Bommon",
    "ブギーモン": "Boogiemon",
    "ボサモン": "Bosamon",
    "ボタモン": "Botamon",
    "バウトモン": "Boutmon",
    "バウモン": "Bowmon",
    "ブラキモン": "Brachimon",
    "ブレイクドラモン": "Breakdramon",
    "ブリガードラモン": "Brigadramon",
    "ブリウエルドラモン": "Bryweludramon",
    "バブモン": "Bubbmon",
    "バドモン": "Budmon",
    "バルクモン": "Bulkmon",
    "ブルモン": "Bullmon",
    "ブン": "Bun",
    "ブライモン": "Buraimon",
    "バーガモン": "Burgamon",
    "バーガモン成熟期": "Burgamon Adult",
    "ばーぷモン": "Burpmon",
    "ブシアグモン": "Bushi Agumon",
    "ブテンモン": "Butenmon",
    "バタフラモン": "Butterflamon",
    "ブーモン": "Būmon",
    "カルマーラモン": "Calamaramon",
    "カリスモン": "Callismon",
    "キャンドモン": "Candmon",
    "キャノンビーモン": "Cannonbeemon",
    "キャノンビーモン （空母型）": "Cannonbeemon (Aircraft Carrier)",
    "キャノンドラモン": "Cannondramon",
    "カノーヴァイスモン": "Canoweissmon",
    "カプリモン": "Caprimon",
    "キャプテンフックモン": "Captain Hookmon",
    "カードモンＣ１": "Cardmon C1",
    "カードモンＣ２": "Cardmon C2",
    "カードモンＲ１": "Cardmon R1",
    "カードモンＲ２": "Cardmon R2",
    "カードモンＳ１": "Cardmon S1",
    "カードモンＳ２": "Cardmon S2",
    "カードモンＵ１": "Cardmon U1",
    "カードモンＵ２": "Cardmon U2",
    "カーゴドラモン": "Cargodramon",
    "キャッチマメモン": "Catch Mamemon",
    "チャツラモン": "Caturamon",
    "サンドリモン": "Cendrillmon",
    "ケンタルモン": "Centalmon",
    "ケルベロモン": "Cerberumon",
    "ケルベロモン（X抗体）": "Cerberumon (X-Antibody)",
    "ケルベロモン：人狼モード": "Cerberumon: Werewolf Mode",
    "ケレスモン": "Ceresmon",
    "ケレスモン メディウム": "Ceresmon Medium",
    "ケルヌモン": "Cernumon",
    "チャックモン": "Chackmon",
    "シャンブルモン": "Chamblemon",
    "カメレモン": "Chamelemon",
    "カオスデュークモン": "Chaos Dukemon",
    "カオスデュークモン コア": "Chaos Dukemon Core",
    "カオスグレイモン": "Chaos Greymon",
    "カオスグリムモン": "Chaos Grimmon",
    "カオスロード": "Chaos Lord",
    "カオスピエモン": "Chaos Piemon",
    "カオスシードラモン": "Chaos Seadramon",
    "カオスドラモン": "Chaosdramon",
    "カオスドラモン（X抗体）": "Chaosdramon (X-Antibody)",
    "カオスモン": "Chaosmon",
    "カオスモン：ヴァロドゥルアーム": "Chaosmon: Valdur Arm",
    "シャペロモン": "Chaperomon",
    "チャップモン": "Chapmon",
    "チアガールモン": "Cheer Galmon",
    "ケルビモン（悪）": "Cherubimon (Vice)",
    "ケルビモン（悪）（X抗体）": "Cherubimon (Vice) (X-Antibody)",
    "ケルビモン（善）": "Cherubimon (Virtue)",
    "ケルビモン（善）（X抗体）": "Cherubimon (Virtue) (X-Antibody)",
    "チビックソード": "Chibick Sword",
    "チビカメモン": "Chibi Kamemon",
    "チビキウイモン": "Chibi Kiwimon",
    "チビックモン": "Chibickmon",
    "チビモン": "Chibimon",
    "チッチモン": "Chicchimon",
    "チコモン": "Chicomon",
    "チクリモン": "Chikurimon",
    "キメラモン": "Chimairamon",
    "キロプモン": "Chiropmon",
    "チョ・ハッカイモン": "Cho·Hakkaimon",
    "チョコモン": "Chocomon",
    "チョロモン": "Choromon",
    "クロノモン デストロイモード": "Chronomon Destroy Mode",
    "クロノモン ホーリーモード": "Chronomon Holy Mode",
    "クリサリモン": "Chrysalimon",
    "クラヴィスエンジェモン": "Clavis Angemon",
    "クリアアグモン": "Clear Agumon",
    "クライモン": "Climbmon",
    "クロックモン": "Clockmon",
    "クアトルモン": "Coatlmon",
    "コカトリモン": "Cockatrimon",
    "ココモン": "Cocomon",
    "シーラモン": "Coelamon",
    "コマンドラモン": "Commandramon",
    "コピモン": "Copymon",
    "コアドラモン（青）": "Coredramon (Blue)",
    "コアドラモン（緑）": "Coredramon (Green)",
    "コロナモン": "Coronamon",
    "コツコモン": "Cotsucomon",
    "クーガモン": "Cougarmon",
    "クレニアムモン": "Craniummon",
    "クレニアムモン（X抗体）": "Craniummon (X-Antibody)",
    "クレニアムモン＋アンヴァルモン": "Craniummon + Enbarrmon",
    "クレシェモン": "Crescemon",
    "クーレスガルルモン": "Cres Garurumon",
    "クロスモン": "Crossmon",
    "クリスペイルドラモン": "Crys Paledramon",
    "クティーラモン": "Cthyllamon",
    "クルモン": "Culumon",
    "キュピモン": "Cupimon",
    "クリモン": "Curimon",
    "キュートモン": "Cutemon",
    "サイバードラモン": "Cyberdramon",
    "サイバードラモン": "Cyberdramon (2010 Anime Version)",
    "サイバードラモン（X抗体）": "Cyberdramon (X-Antibody)",
    "サイクロモン": "Cyclomon",
    "ダゴモン": "Dagomon",
    "ダイペンモン": "Daipenmon",
    "ダルフォモン": "Dalphomon",
    "ダメモン": "Damemon",
    "ダンモン": "Danmon",
    "ダルクモン": "Darcmon",
    "ダークナイトモン": "Dark Knightmon",
    "ダークナイトモン（X抗体）": "Dark Knightmon (X-Antibody)",
    "ダークナイトモン": "Dark Knightmon (Bagramon)",
    "ダークリザモン": "Dark Lizamon",
    "ダークメイルドラモン": "Dark Maildramon",
    "ダークスーパースターモン": "Dark Superstarmon",
    "ダークティラノモン": "Dark Tyranomon",
    "ダークティラノモン（X抗体）": "Dark Tyranomon (X-Antibody)",
    "ダークボリューモン": "Dark Volumon",
    "ダークドラモン": "Darkdramon",
    "ダークネスバグラモン": "Darkness Bagramon",
    "ダルマモン": "Darumamon",
    "大雪人兽": "Daxuerenshou",
    "デッドリーアックスモン": "Deadly Axemon",
    "デッドリーツワーモン": "Deadly Tuwarmon",
    "デッドリーツワーモン ヘルモード": "Deadly Tuwarmon Hell Mode",
    "デスエアドラモン": "Death Airdramon",
    "デスデビモン": "Death Devimon",
    "デスメラモン": "Death Meramon",
    "デスメラモン": "Death Meramon (C'mon Digimon Version)",
    "デスメタルグレイモン": "Death Metal Greymon",
    "デスティラノモン": "Death Tyranomon",
    "デクスドルガモン": "Death-X-DORUgamon",
    "デクスドルゴラモン": "Death-X-DORUgoramon",
    "デクスドルグレモン": "Death-X-DORUguremon",
    "デクスモン": "Death-X-mon",
    "デスモン": "Deathmon",
    "デスモン（黒）": "Deathmon (Black)",
    "デスモン": "Deathmon (C'mon Digimon Version)",
    "デッカーグレイモン": "Decker Greymon",
    "デッカードラモン": "Deckerdramon",
    "デッカードラモン フロートモード": "Deckerdramon Float Mode",
    "デルタモン": "Deltamon",
    "デラモン": "Delumon",
    "デーモン": "Demon",
    "デーモン超究極体": "Demon Super Ultimate",
    "デーモン（X抗体）": "Demon (X-Antibody)",
    "デプスモン": "Depthmon",
    "デストロモン": "Destromon",
    "デビドラモン": "Devidramon",
    "デビモン": "Devimon",
    "デビタマモン": "Devitamamon",
    "ディアボロモン": "Diablomon",
    "ディアボロモン（X抗体）": "Diablomon (X-Antibody)",
    "ディアナモン": "Dianamon",
    "ディルビットモン": "Diarbbitmon",
    "ディアトリモン": "Diatrymon",
    "デジタマモン": "Digitamamon",
    "ディグモン": "Digmon",
    "ディージャンモン": "Dijiangmon",
    "ディメトロモン": "Dimetromon",
    "ディノビーモン": "Dinobeemon",
    "ディノヒューモン": "Dinohumon",
    "ダイナモン": "Dinomon",
    "ディノレクスモン": "Dinorexmon",
    "ディノタイガモン": "Dinotigermon",
    "ダイブモン": "Divemon",
    "ドーベルモン": "Dobermon",
    "ドーベルモン（X抗体）": "Dobermon (X-Antibody)",
    "ドドモン": "Dodomon",
    "ドッグモン": "Dogmon",
    "ドキモン": "Dokimon",
    "ドクグモン": "Dokugumon",
    "ドクネモン": "Dokunemon",
    "ドミニモン": "Dominimon",
    "ドンドコモン": "Dondokomon",
    "ドンシャウトモン": "Don Shoutmon",
    "ダンデビモン": "Done Devimon",
    "ドルビックモン": "Dorbickmon",
    "ドルビックモンダークネスモード": "Dorbickmon Darkness Mode (Huanglongmon)",
    "ドリモン": "Dorimon",
    "ドルガモン": "DORUgamon",
    "ドルゴラモン": "DORUgoramon",
    "ドルグレモン": "DORUguremon",
    "ドルルモン": "Dorulumon",
    "ドルモン": "DORUmon",
    "ドットアグモン": "Dot Agumon",
    "ドットファルコモン": "Dot Falcomon",
    "ドットガオモン": "Dot Gaomon",
    "ドットカメモン": "Dot Kamemon",
    "ドットクダモン": "Dot Kudamon",
    "ドットララモン": "Dot Lalamon",
    "ドットミラージュガオガモン": "Dot Mirage Gaogamon",
    "ドットシャイングレイモン": "Dot Shine Greymon",
    "ドウモン": "Doumon",
    "ドラコモン": "Dracomon",
    "ドラコモン（X抗体）": "Dracomon (X-Antibody)",
    "ドラクモン": "Dracumon",
    "ドリモゲモン": "Drimogemon",
    "ドゥフトモン": "Duftmon",
    "ドゥフトモン（X抗体）": "Duftmon (X-Antibody)",
    "ドゥフトモン：レオパルドモード": "Duftmon: Leopard Mode",
    "デュークモン": "Dukemon",
    "デュークモン：クリムゾンモード": "Dukemon: Crimson Mode",
    "デュークモン（X抗体）": "Dukemon (X-Antibody)",
    "デュラハモン": "Dullahamon",
    "デュランダモン": "Duramon",
    "デュラモン": "Durandamon",
    "ダスクモン": "Duskmon",
    "デュナスモン": "Dynasmon",
    "デュナスモン（X抗体）": "Dynasmon (X-Antibody)",
    "アースドラモン": "Earthdramon",
    "イーバモン": "EBEmon",
    "イーバモン（X抗体）": "EBEmon (X-Antibody)",
    "エビバーガモン": "Ebi Burgamon",
    "エビドラモン": "Ebidramon",
    "エカキモン": "Ekakimon",
    "エルドラディモン": "El Doradimon",
    "エレキモン": "Elecmon",
    "エレキモン（紫）": "Elecmon (Violet)",
    "エレファモン": "Elephamon",
    "エリザモン": "Elizamon",
    "アンヴァルモン": "Enbarrmon",
    "エンマモン": "Enmamon",
    "エントモン": "Entmon",
    "エオスモン（成熟期）": "Eosmon (Adult)",
    "エオスモン（完全体）": "Eosmon (Perfect)",
    "エオスモン（究極体）": "Eosmon (Ultimate)",
    "イーランモン": "Erlangmon",
    "イーランモン：ブラストモード": "Erlangmon: Blast Mode",
    "エスピモン": "Espimon",
    "エテモン": "Etemon",
    "エテモンカオス": "Etemon Chaos",
    "イビルモン": "Evilmon",
    "エクスマキナモン": "Ex Maquinamon",
    "エクスティラノモン": "Ex-Tyranomon",
    "エグザモン": "Examon",
    "エグザモン（X抗体）": "Examon (X-Antibody)",
    "エキサモン": "Exermon",
    "エグゾグリムモン": "Exo Grimmon",
    "アイズモン": "Eyesmon",
    "アイズモン：スキャッターモード": "Eyesmon: Scatter Mode",
    "フェアリモン": "Fairimon",
    "ファルコモン": "Falcomon",
    "ファルコモン（２００６アニメ版）": "Falcomon (2006 Anime Version)",
    "ファングモン": "Fangmon",
    "ファントモン": "Fantomon",
    "フェンリルガモン": "Fenriloogamon",
    "フェンリルガモン：建御雷神": "Fenriloogamon: Takemikazuchi",
    "フィルモン": "Filmon",
    "ファイラモン": "Firamon",
    "フレイウィザーモン": "Fla Wizarmon",
    "フレイドラモン": "Fladramon",
    "フレイモン": "Flamon",
    "フレアリザモン": "Flare Lizamon",
    "フレアモン": "Flaremon",
    "フローラモン": "Floramon",
    "フラフィモン": "Fluffymon",
    "フライビーモン": "Flybeemon",
    "フライモン": "Flymon",
    "フットモン": "Footmon",
    "フォージビーモン": "Forgebeemon",
    "フリモン": "Frimon",
    "フロッグモン": "Frogmon",
    "フロスベルグモン": "Fros Velgrmon",
    "フロゾモン": "Frozomon",
    "フフモン": "Fufumon",
    "フーガモン": "Fugamon",
    "フージャモン": "Fujamon",
    "フウジンモン": "Fujinmon",
    "フジツモン": "Fujitsumon",
    "フカモン": "Fukamon",
    "フウマモン": "Fumamon",
    "ファンビーモン": "Funbeemon",
    "フサモン": "Fusamon",
    "グレイテストキュートモン": "G-Cutemon",
    "ガブモン": "Gabumon",
    "ガブモン（X抗体）": "Gabumon (X-Antibody)",
    "ガブモン（黒）": "Gabumon (Black)",
    "ガブモン -友情の絆-": "Gabumon -Yujo no Kizuna-",
    "ガイアモン": "Gaiamon",
    "ガイオウモン": "Gaioumon",
    "ガイオウモン：厳刀ノ型": "Gaioumon: Itto Mode",
    "ゲイルモン": "Galemon",
    "ガルゴモン": "Galgomon",
    "ガンマモン": "Gammamon",
    "ガネモン": "Ganemon",
    "ガニモン": "Ganimon",
    "ガニモン（X抗体）": "Ganimon (X-Antibody)",
    "ガンクゥモン": "Gankoomon",
    "ガンクゥモン（X抗体）": "Gankoomon (X-Antibody)",
    "ガンバイバーモン": "Ganvivormon",
    "ガオガモン": "Gaogamon",
    "ガオモン": "Gaomon",
    "ガオスモン": "Gaossmon",
    "ガーゴモン": "Gargomon",
    "ガルダモン": "Garudamon",
    "ガルダモン（X抗体）": "Garudamon (X-Antibody)",
    "ガルムモン": "Garummon",
    "ガルルモン": "Garurumon",
    "ガルルモン（X抗体）": "Garurumon (X-Antibody)",
    "ガルルモン（黒）": "Garurumon (Black)",
    "ガサモン": "Gasamon",
    "合体エンシェントボルケーモン": "Gattai Ancient Volcamon",
    "合体リリスモン": "Gattai Lilithmon",
    "ガワッパモン": "Gawappamon",
    "ガジモン": "Gazimon",
    "ガジモン（X抗体）": "Gazimon (X-Antibody)",
    "ゲッコーモン": "Gekkomon",
    "ゲコモン": "Gekomon",
    "ジェムモン": "Gemmon",
    "ジェネラモン": "Generamon",
    "ジオグレイモン": "Geo Greymon",
    "ガーベモン": "Gerbemon",
    "ゲレモン": "Geremon",
    "ゲソモン": "Gesomon",
    "ゲソモン（X抗体）": "Gesomon (X-Antibody)",
    "ギリードゥモン": "Ghilliedhumon",
    "ゴースモン": "Ghostmon",
    "ギガブレイクドラモン": "Giga Breakdramon",
    "ギガシードラモン": "Giga Seadramon",
    "ギガワルもんざえモン": "Giga Waru Monzaemon",
    "ギガドラモン": "Gigadramon",
    "巨大ヌメモン": "Gigantic Numemon",
    "巨大パンプモン": "Gigantic Pumpmon",
    "ギガスモン": "Gigasmon",
    "ギギモン": "Gigimon",
    "ギンカクモン": "Ginkakumon",
    "ギンカクモンプロモート": "Ginkakumon Promote",
    "ギンリュウモン": "Ginryumon",
    "ギロモン": "Giromon",
    "ギザモン": "Gizamon",
    "ギズモン：ＡＴ": "Gizmon: AT",
    "ギズモン：ＸＴ": "Gizmon: XT",
    "グラディモン": "Gladimon",
    "ゴートモン": "Goatmon",
    "ゴブリモン": "Goburimon",
    "ゴッドドラモン": "Goddramon",
    "ゴッドドラモン（X抗体）": "Goddramon (X-Antibody)",
    "ゴグマモン": "Gogmamon",
    "ゴキモン": "Gokimon",
    "ゴクモン": "Gokumon",
    "ゴクウモン": "Gokuwmon",
    "ゴールドヌメモン": "Gold Numemon",
    "ゴールドヌメモン": "Gold Numemon (Ultimate)",
    "ゴールドブイドラモン": "Gold V-dramon",
    "ゴーレムジジカメモン": "Golem Jiji Kamemon",
    "ゴーレモン": "Golemon",
    "ゴーレモン": "Golemon (PS)",
    "ゴマモン": "Gomamon",
    "ゴマモン（X抗体）": "Gomamon (X-Antibody)",
    "ゴリモン": "Gorimon",
    "ゴロモン": "Goromon",
    "ゴツモン": "Gottsumon",
    "ゴツモン（X抗体）": "Gottsumon (X-Antibody)",
    "グレイスノヴァモン": "Grace Novamon",
    "グレイドモン": "Grademon",
    "グレイドモン（悪）": "Grademon (Vice)",
    "グランクワガーモン": "Gran Kuwagamon",
    "グランドラクモン": "Grand Dracumon",
    "グランゲイルモン": "Grand Galemon",
    "グランドジェネラモン": "Grand Generamon",
    "グランドロコモン": "Grand Locomon",
    "グランディスクワガーモン": "Grandis Kuwagamon",
    "グランディスクワガーモンハニーモード": "Grandis Kuwagamon Honey Mode",
    "グラップレオモン": "Grappu Leomon",
    "グラビモン": "Gravimon",
    "グラビモンダークネスモード": "Gravimon Darkness Mode",
    "グレートグリズモン": "Great Gryzmon",
    "スカモン大王": "Great King Scumon",
    "グレイナイツモン": "Grey Knightsmon",
    "グレイモン": "Greymon",
    "グレイモン（X抗体）": "Greymon (X-Antibody)",
    "グレイモン": "Greymon (2010 Anime Version)",
    "グレイモン (灰)": "Greymon (Ash)",
    "グレイモン（青）": "Greymon (Blue)",
    "グレイモン（青）（X抗体）": "Greymon (Blue) (X-Antibody)",
    "グレイモン (橙)": "Greymon O",
    "グリフォモン": "Griffomon",
    "グリムモン": "Grimmon",
    "グロットモン": "Grottemon",
    "グラウンドラモン": "Groundramon",
    "グラウモン": "Growmon",
    "グラウモン（X抗体）": "Growmon (X-Antibody)",
    "グラウモン": "Growmon (Orange)",
    "グリズモン": "Gryzmon",
    "ガードロモン": "Guardromon",
    "ガードロモン（金）": "Guardromon (Gold)",
    "ガイドモン": "Guidemon",
    "ギルモン": "Guilmon",
    "ギルモン（X抗体）": "Guilmon (X-Antibody)",
    "ガルフモン": "Gulfmon",
    "グルスガンマモン": "Gulus Gammamon",
    "ガムドラモン": "Gumdramon",
    "グミモン": "Gummymon",
    "ガンドラモン": "Gundramon",
    "グリモン": "Gurimon",
    "グルルモン": "Gururumon",
    "グソクモン": "Gusokumon",
    "ギュウキモン": "Gyukimon",
    "ハバキリモン": "Habakirimon",
    "ハックモン": "Hackmon",
    "ハグルモン": "Hagurumon",
    "ハグルモン（X抗体）": "Hagurumon (X-Antibody)",
    "ハクバモン": "Hakubamon",
    "ハンギョモン": "Hangyomon",
    "ハニモン": "Hanimon",
    "ハヌモン": "Hanumon",
    "ハーピモン": "Harpymon",
    "ホークモン": "Hawkmon",
    "ヘヴィーレオモン": "Heavy Leomon",
    "ヘヴィーメタルドラモン": "Heavy Metaldramon",
    "ヘルガルモン": "Helloogarmon",
    "ヘラクルカブテリモン": "Herakle Kabuterimon",
    "ヘラクルカブテリモン（X抗体）": "Herakle Kabuterimon (X-Antibody)",
    "エリスモン": "Herissmon",
    "ヘルムモン": "Hermmon",
    "何首乌兽": "Heshouwushou",
    "ヘクセブラウモン": "Hexeblaumon",
    "ハイアンドロモン": "Hi Andromon",
    "ハイムゲンドラモン": "Hi Mugendramon",
    "ハイコマンドラモン": "Hi-Commandramon",
    "ハイビジョンモニタモン": "Hi-Vision Monitamon",
    "ヒポグリフォモン": "Hippogriffomon",
    "ヒシャリュウモン": "Hisyaryumon",
    "ヒヤリモン": "Hiyarimon",
    "ホルスモン": "Holsmon",
    "ホーリーエンジェモン": "Holy Angemon",
    "ホーリーエンジェモン：神官形態": "Holy Angemon: Priest Mode",
    "ホーリーデジタマモン": "Holy Digitamamon",
    "ホーリードラモン": "Holydramon",
    "ホーリードラモン（X抗体）": "Holydramon (X-Antibody)",
    "ハニービーモン": "Honeybeemon",
    "フックモン": "Hookmon",
    "ホップモン": "Hopmon",
    "ホウオウモン": "Hououmon",
    "ホウオウモン（X抗体）": "Hououmon (X-Antibody)",
    "ホバーエスピモン": "Hover Espimon",
    "ファンロンモン": "Huanglongmon",
    "ファンロンモン：ルインモード": "Huanglongmon: Ruin Mode",
    "ファンクンモン": "Huankunmon",
    "ハブモン": "Hubmon",
    "フーディエモン": "Hudiemon",
    "ハンターモン": "Huntermon",
    "ハッスルナニモン": "Hustle Nanimon",
    "ヒュドラモン": "Hydramon",
    "ハイエモン": "Hyemon",
    "ヒョコモン": "Hyokomon",
    "ヒョーガモン": "Hyougamon",
    "アイスデビモン": "Ice Devimon",
    "アイスデビモン 強化吸収体": "Ice Devimon Enhancement Absorbent",
    "アイスデビモン ダイペンモン 強化吸収体": "Ice Devimon Daipenmon Enhancement Absorbent",
    "アイスモン": "Icemon",
    "イガモン": "Igamon",
    "イグニートモン": "Iguneetmon",
    "イッカクモン": "Ikkakumon",
    "インペリアルドラモン：ドラゴンモード": "Imperialdramon: Dragon Mode",
    "インペリアルドラモン：ドラゴンモード（黒）": "Imperialdramon: Dragon Mode (Black)",
    "インペリアルドラモン：ファイターモード": "Imperialdramon: Fighter Mode",
    "インペリアルドラモン：ファイターモード（黒）": "Imperialdramon: Fighter Mode (Black)",
    "インペリアルドラモン：パラディンモード": "Imperialdramon: Paladin Mode",
    "インプモン": "Impmon",
    "インプモン（X抗体）": "Impmon (X-Antibody)",
    "インダラモン": "Indaramon",
    "インフェルモン": "Infermon",
    "インセキモン": "Insekimon",
    "インビジモン": "Invisimon",
    "ジャザモン": "Jazamon",
    "ジャザードモン": "Jazardmon",
    "ジャザリッヒモン": "Jazarichmon",
    "ジェリーモン": "Jellymon",
    "ジエスモン": "JESmon",
    "ジエスモン（X抗体）": "JESmon (X-Antibody)",
    "ジエスモンGX": "JESmon GX",
    "ジェットメルヴァモン": "Jet Mervamon",
    "ジェットシルフィーモン": "Jet Silphymon",
    "ジュエルビーモン": "Jewelbeemon",
    "ジジモン": "Jijimon",
    "ジジシャウトモン": "Jiji Shoutmon",
    "ジコチューモン": "Jiko Chuumon",
    "金丝猴兽": "Jinsihoushou",
    "ジョーカーモン": "Jokermon",
    "ジョウガモン": "Jougamon",
    "ジャンボガメモン": "Jumbo Gamemon",
    "ジャングルモジャモン": "Jungle Mojyamon",
    "ジャンクモン": "Junkmon",
    "ユノモン": "Junomon",
    "ユノモン：ヒステリックモード": "Junomon: Hysteric Mode",
    "ユピテルモン": "Jupitermon",
    "ユピテルモン：ラースモード": "Jupitermon: Wrath Mode",
    "ジャスティモン（X抗体）": "Justimon (X-Antibody)",
    "ジャスティモン：アクセルアーム": "Justimon: Accel Arm",
    "ジャスティモン：ブリッツアーム": "Justimon: Blitz Arm",
    "ジャスティモン：クリティカルアーム": "Justimon: Critical Arm",
    "ジャガモン": "Jyagamon",
    "ジャリモン": "Jyarimon",
    "ジュレイモン": "Jyureimon",
    "ジュレイモン": "Jyureimon (Christmas Tree)",
    "カブキモン": "Kabukimon",
    "カブテリモン": "Kabuterimon",
    "カラクルモン": "Kaguyamon",
    "カイゼルグレイモン": "Kaiser Greymon",
    "カイザーレオモン": "Kaiser Leomon",
    "カカモン": "Kakamon",
    "カッキンモン": "Kakkinmon",
    "カメモン": "Kamemon",
    "カミナリモン": "Kaminarimon",
    "かんどうしちゃうんだもん": "Kandoushichaundamon",
    "カンガルモン": "Kangarumon",
    "カラクルモン": "Karakurumon",
    "カラテンモン": "Karatenmon",
    "カラツキヌメモン": "Karatuki Numemon",
    "カウスガンマモン": "Kaus Gammamon",
    "カヅチモン": "Kazuchimon",
    "キーモン": "Keemon",
    "ケッコモン": "Kekkomon",
    "ケコモン": "Kekomon",
    "ケンキモン": "Kenkimon",
    "ケラモン": "Keramon",
    "ケラモン（X抗体）": "Keramon (X-Antibody)",
    "ケトモン": "Ketomon",
    "キングチェスモン": "King Chessmon",
    "キングエテモン": "King Etemon",
    "キングハンギョモン": "King Hangyomon",
    "キングホエーモン": "King Whamon",
    "キンカクモン": "Kinkakumon",
    "キタキツネモン": "Kita Kitsunemon",
    "キウイモン": "Kiwimon",
    "ナイトチェスモン（黒）": "Knight Chessmon (Black)",
    "ナイトチェスモン（白）": "Knight Chessmon (White)",
    "ナイトモン": "Knightmon",
    "ナイトモンワイズソードモード": "Knightmon Wise Sword Mode",
    "コドクグモン": "Kodokugumon Baby",
    "コドクグモン": "Kodokugumon Child",
    "コエモン": "Koemon",
    "コハグルモン": "Kohagurumon",
    "コカブテリモン": "Kokabuterimon",
    "コケシモン": "Kokeshimon",
    "コクワモン": "Kokuwamon",
    "コクワモン（X抗体）": "Kokuwamon (X-Antibody)",
    "コモンドモン": "Komondomon",
    "コンゴウモン": "Kongoumon",
    "コロモン": "Koromon",
    "コテモン": "Kotemon",
    "コウガモン": "Kougamon",
    "コゼニモン": "Kozenimon",
    "クダモン": "Kudamon",
    "クダモン（２００６アニメ版）": "Kudamon (2006 Anime Version)",
    "クンビラモン": "Kumbhiramon",
    "クネモン": "Kunemon",
    "クラモン": "Kuramon",
    "クワガーモン": "Kuwagamon",
    "クワガーモン（X抗体）": "Kuwagamon (X-Antibody)",
    "クズハモン": "Kuzuhamon",
    "クズハモン：巫女モード": "Kuzuhamon: Miko Mode",
    "キャロモン": "Kyaromon",
    "キョキョモン": "Kyokyomon",
    "キュウビモン": "Kyubimon",
    "キュウビモン（銀）": "Kyubimon (Silver)",
    "キュウカンチョウモン": "Kyukanchoumon",
    "キュウキモン": "Kyukimon",
    "ラブラモン": "Labramon",
    "レディーデビモン": "Lady Devimon",
    "レディーデビモン（X抗体）": "Lady Devimon (X-Antibody)",
    "レウスグレイモン": "Laeus Greymon",
    "ララモン": "Lalamon",
    "ラミアモン": "Lamiamon",
    "ラモールモン": "Lamortmon",
    "ランプモン": "Lampmon",
    "ランドラモン": "Landramon",
    "ラヴォガリータモン": "Lavogaritamon",
    "ラヴォーボモン": "Lavorvomon",
    "リーフモン": "Leafmon",
    "レキスモン": "Lekismon",
    "レオモン": "Leomon",
    "レオモン（X抗体）": "Leomon (X-Antibody)",
    "リヴァイアモン": "Leviamon",
    "リヴァイアモン（X抗体）": "Leviamon (X-Antibody)",
    "ライアモン": "Liamon",
    "リェンフーモン": "Lianpumon",
    "ライドラモン": "Lighdramon",
    "ライラモン": "Lilamon",
    "リリモン": "Lilimon",
    "リリモン（X抗体）": "Lilimon (X-Antibody)",
    "リリスモン": "Lilithmon",
    "リリスモン（X抗体）": "Lilithmon (X-Antibody)",
    "レオルモン": "Liollmon",
    "リスクモン": "Liskmon",
    "ローダーレオモン": "Loader Leomon",
    "ロコモン": "Locomon",
    "ルガモン": "Loogamon",
    "ルガルモン": "Loogarmon",
    "ロップモン": "Lopmon",
    "ロップモン（X抗体）": "Lopmon (X-Antibody)",
    "ロードナイトモン": "Lord Knightmon",
    "ロードナイトモン（X抗体）": "Lord Knightmon (X-Antibody)",
    "ロトスモン": "Lotusmon",
    "ラウドモン": "Loudmon",
    "ラブリーエンジェモン": "Lovely Angemon",
    "レーベモン": "Löwemon",
    "ルーチェモン": "Lucemon",
    "ルーチェモン：フォールダウンモード": "Lucemon: Falldown Mode",
    "ルーチェモン：ラルバ": "Lucemon: Larva",
    "ルーチェモン：サタンモード": "Lucemon: Satan Mode",
    "ルーチェモン（X抗体）": "Lucemon (X-Antibody)",
    "ルドモン": "Ludomon",
    "ルミナモン": "Luminamon",
    "ルミナモン（ネネＶｅｒ.）": "Luminamon (Nene Ver.)",
    "ルナモン": "Lunamon",
    "ルクスモン": "Luxmon",
    "リュカモン": "Lykamon",
    "ランクスモン": "Lynxmon",
    "マッハガオガモン": "Mach Gaogamon",
    "マッハレオモン": "Mach Leomon",
    "マッハモン": "Machmon",
    "マッドレオモン": "Mad Leomon",
    "マッドレオモン（ファイナルモード）": "Mad Leomon (Final Mode)",
    "マッドレオモン（オロチモード）": "Mad Leomon (Orochi Mode)",
    "マッドレオモン：アームドモード": "Mad Leomon: Armed Mode",
    "マドモン": "Madomon",
    "マグナガルルモン": "Magna Garurumon",
    "マグナキッドモン": "Magna Kidmon",
    "マグナモン": "Magnamon",
    "マグナモン（X抗体）": "Magnamon (X-Antibody)",
    "マグネティックドラモン": "Magneticdramon",
    "メイルバードラモン": "Mail Birdramon",
    "メイルドラモン": "Maildramon",
    "マジラモン": "Majiramon",
    "魔獣リリスモン": "Majuu Lilithmon",
    "マクラモン": "Makuramon",
    "マメモン": "Mamemon",
    "マメモン（X抗体）": "Mamemon (X-Antibody)",
    "マメティラモン": "Mametyramon",
    "マンモン": "Mammon",
    "マンモン（X抗体）": "Mammon (X-Antibody)",
    "マンボモン": "Manbomon",
    "マネキモン": "Manekimon",
    "マニューバモン": "Maneuvermon",
    "マンタレイモン": "Mantaraymon",
    "マンタレイモン（X抗体）": "Mantaraymon (X-Antibody)",
    "マンティコアモン": "Manticoremon",
    "マキナモン": "Maquinamon",
    "マリンエンジェモン": "Marin Angemon",
    "マリンブルモン": "Marin Bullmon",
    "マリンキメラモン": "Marin Chimairamon",
    "マリンデビモン": "Marin Devimon",
    "マルスモン": "Marsmon",
    "マスティモン": "Mastemon",
    "主": "Master",
    "マスターブリンプモン": "Master Blimpmon",
    "マスターティラノモン": "Master Tyranomon",
    "マスターブイドラモン": "Master V-dramon",
    "マタドゥルモン": "Matadrmon",
    "メカノリモン": "Mechanorimon",
    "メディーバルデュークモン": "Medieval Dukemon",
    "メデューサモン": "Medusamon",
    "メガブラックシャウトモンＸ７": "Mega Black Shoutmon X7",
    "メガダークナイトモン": "Mega Dark Knightmon",
    "メガダークネスバグラモン": "Mega Darkness Bagramon",
    "メガデッカーグレイモン": "Mega Decker Greymon",
    "メガドラモン": "Megadramon",
    "メガグランクワガーモン": "Mega Gran Kuwagamon",
    "メガムソーナイトモン": "Mega Muso Knightmon",
    "メガシードラモン": "Mega Seadramon",
    "メガシードラモン（X抗体）": "Mega Seadramon (X-Antibody)",
    "メガログラウモン": "Megalo Growmon",
    "メガログラウモン（X抗体）": "Megalo Growmon (X-Antibody)",
    "メガログラウモン": "Megalo Growmon (Orange)",
    "メギドラモン": "Megidramon",
    "メギドラモン（X抗体）": "Megidramon (X-Antibody)",
    "メイクーモン": "Meicoomon",
    "メイクラックモン": "Meicrackmon",
    "メイクラックモンヴィシャスモード": "Meicrackmon: Vicious Mode",
    "メフィスモン": "Mephismon",
    "メフィスモン（X抗体）": "Mephismon (X-Antibody)",
    "メラモン": "Meramon",
    "メラモン（X抗体）": "Meramon (X-Antibody)",
    "メルキューレモン": "Mercuremon",
    "メルクリモン": "Mercurymon",
    "マーメイモン": "Mermaimon",
    "メルヴァモン": "Mervamon",
    "メルヴァモン ワイドハイビジョンソード": "Mervamon Wide Hi-Vision Sword",
    "メタルエテモン": "Metal Etemon",
    "メタルファントモン": "Metal Fantomon",
    "メタルガルルモン": "Metal Garurumon",
    "メタルガルルモン（X抗体）": "Metal Garurumon (X-Antibody)",
    "メタルガルルモン": "Metal Garurumon (Black)",
    "メタルガルルモン (赤)": "Metal Garurumon (Red)",
    "メタルグレイモン": "Metal Greymon",
    "メタルグレイモン（X抗体）": "Metal Greymon (X-Antibody)",
    "メタルグレイモン": "Metal Greymon (2010 Anime Version)",
    "メタルグレイモン": "Metal Greymon (Virus)",
    "メタルグレイモン（ウィルス種）（X抗体）": "Metal Greymon (Virus) (X-Antibody)",
    "メタルグレイモン＋サイバーランチャー": "Metal Greymon + Cyber Launcher",
    "メタルグレイモン: \"G\" 侵食モード": "Metal Greymon: \"G\" Erosion Mode",
    "メタルグレイモン：アルタラウスモード": "Metal Greymon: Alterous Mode",
    "メタルマメモン": "Metal Mamemon",
    "メタルマメモン（X抗体）": "Metal Mamemon (X-Antibody)",
    "メタルピラニモン": "Metal Piranimon",
    "メタルシードラモン": "Metal Seadramon",
    "メタルティラノモン": "Metal Tyranomon",
    "メタルティラノモン（X抗体）": "Metal Tyranomon (X-Antibody)",
    "メタリックドラモン": "Metallicdramon",
    "メタリフェクワガーモン": "Metallife Kuwagamon",
    "メタモルモン": "Metamormon",
    "メタトロモン": "Metatromon",
    "ミヒラモン": "Mihiramon",
    "ミケモン": "Mikemon",
    "ミレニアモン": "Millenniumon",
    "ミミクモン": "Mimicmon",
    "ミネルヴァモン": "Minervamon",
    "ミネルヴァモン（X抗体）": "Minervamon (X-Antibody)",
    "ミニデカチモン": "Minidekachimon",
    "ミノモン": "Minomon",
    "ミノタルモン": "Minotaurmon",
    "ミラージュガオガモン": "Mirage Gaogamon",
    "ミラージュガオガモン：バーストモード": "Mirage Gaogamon: Burst Mode",
    "ミラーボールモン": "Mirror Ballmon",
    "ミサイモン": "Missimon",
    "ミスティモン": "Mistymon",
    "ミタマモン": "Mitamamon",
    "モチモン": "Mochimon",
    "モッキンバーモン": "Mockingbirdmon",
    "モココモン": "Mococomon",
    "モドキベタモン": "Modoki Betamon",
    "モジャモン": "Mojyamon",
    "モクモン": "Mokumon",
    "モナークリザモン": "Monarch Lizamon",
    "モニモン": "Monimon",
    "モニタモン": "Monitamon",
    "モノクロモン": "Monochromon",
    "モノクロモン（X抗体）": "Monochromon (X-Antibody)",
    "モノドラモン": "Monodramon",
    "もんざえモン": "Monzaemon",
    "もんざえモン（X抗体）": "Monzaemon (X-Antibody)",
    "ムーン＝ミレニアモン": "Moon Millenniumon",
    "ムンモン": "Moonmon",
    "ムースモン": "Moosemon",
    "モリシェルモン": "Mori Shellmon",
    "モルフォモン": "Morphomon",
    "モスモン": "Mothmon",
    "木偶兽": "Mu'oushou",
    "ムーチョモン": "Muchomon",
    "ムゲンドラモン": "Mugendramon",
    "ムゲンドラモン:3式<改>モード": "Mugendramon: MFS-3 Mode",
    "ミュールモン": "Mulemon",
    "マミーモン": "Mummymon",
    "ムラサメモン": "Murasamemon",
    "ムルムクスモン": "Murmukusmon",
    "マッシュアップド マッハレオモン": "Mush-Upped Mach Leomon",
    "マッシュモン": "Mushmon",
    "ムソーナイトモン": "Muso Knightmon",
    "ムシャモン": "Musyamon",
    "ナマケモン": "Namakemon",
    "ナニモン": "Nanimon",
    "ナノモン": "Nanomon",
    "ナビモーン": "Navimon",
    "ネーモン": "Neamon",
    "ネクロモン": "Necromon",
    "ネフェルティモン": "Nefertimon",
    "ネフェルティモン（X抗体）": "Nefertimon (X-Antibody)",
    "ネガーモン": "Negamon",
    "ネガーモン": "Negamon (Evolved Form)",
    "ネオデビモン": "Neo Devimon",
    "ネオヴァンデモン": "Neo Vamdemon",
    "ネオヴァンデモンダークネスモード": "Neo Vamdemon Darkness Mode (Metal Greymon)",
    "ネプトゥーンモン": "Neptunemon",
    "ナタモン": "Nezhamon",
    "ナタモン：クリムゾンモード": "Nezhamon: Crimson Mode",
    "ニーズヘッグモン": "Nidhoggmon",
    "ナイトキロプモン": "Night Chiropmon",
    "にっこりモン": "Nikkorimon",
    "ニセアグモン博士": "Nise Agumon Hakase",
    "ニセドリモゲモン": "Nise Drimogemon",
    "ノーブルパンプモン": "Noble Pumpmon",
    "ノヘモン": "Nohemon",
    "ヌメモン": "Numemon",
    "ヌメモン（X抗体）": "Numemon (X-Antibody)",
    "女娲兽": "Nüwashou",
    "ニャブートモン": "Nyabootmon",
    "ニャロモン": "Nyaromon",
    "ニョキモン": "Nyokimon",
    "オブリビモン": "Oblivimon",
    "オボロモン": "Oboromon",
    "オチムシャモン": "Ochi Musyamon",
    "オクタモン": "Octmon",
    "オファニモン": "Ofanimon",
    "オファニモン（X抗体）": "Ofanimon (X-Antibody)",
    "オファニモン コア": "Ofanimon Core",
    "オファニモン：フォールダウンモード": "Ofanimon: Falldown Mode",
    "オファニモン：フォールダウンモード（X抗体）": "Ofanimon: Falldown Mode (X-Antibody)",
    "オグドモン": "Ogudomon",
    "オグドモン（X抗体）": "Ogudomon (X-Antibody)",
    "おはかだモン": "Ohakadamon",
    "オクニモン": "Okunimon",
    "オオクワモン": "Okuwamon",
    "オオクワモン（X抗体）": "Okuwamon (X-Antibody)",
    "オウリアモン": "Oleamon",
    "オレーグモン": "Olegmon",
    "オメダモン": "Omedamon",
    "オメガシャウトモン": "Omega Shoutmon",
    "オメガシャウトモン（X抗体）": "Omega Shoutmon (X-Antibody)",
    "オメガモン": "Omegamon",
    "オメガモンＡｌｔｅｒ－Ｂ": "Omegamon Alter-B",
    "オメガモンＡｌｔｅｒ－Ｓ": "Omegamon Alter-S",
    "オメガモン（X抗体）": "Omegamon (X-Antibody)",
    "オメガモンズワルトDEFEAT": "Omegamon Zwart Defeat",
    "オメガモン ズワルト": "Omegamon Zwart",
    "オメガモン：マーシフルモード": "Omegamon: Merciful Mode",
    "オメカモン": "Omekamon",
    "オニビモン": "Onibimon",
    "オポッサモン": "Opossummon",
    "オルカモン": "Orcamon",
    "オルディネモン": "Ordinemon",
    "オーガモン": "Orgemon",
    "オーガモン（X抗体）": "Orgemon (X-Antibody)",
    "オニスモン": "Ornismon",
    "オロチモン": "Orochimon",
    "オタマモン": "Otamamon",
    "オタマモン（X抗体）": "Otamamon (X-Antibody)",
    "オタマモン（赤）": "Otamamon (Red)",
    "オウリュウモン": "Ouryumon",
    "アウルモン": "Owlmon",
    "パフモン": "Pafumon",
    "パグモン": "Pagumon",
    "パイルドラモン": "Paildramon",
    "パジラモン": "Pajiramon",
    "ペイルドラモン": "Paledramon",
    "パルモン": "Palmon",
    "パルモン（X抗体）": "Palmon (X-Antibody)",
    "パンバチモン": "Panbachimon",
    "パンダモン": "Pandamon",
    "パニモン": "Panimon",
    "パンジャモン": "Panjyamon",
    "パンジャモン（X抗体）": "Panjyamon (X-Antibody)",
    "パオモン": "Paomon",
    "パラレルモン": "Parallelmon",
    "パラサウモン": "Parasaurmon",
    "パラサイモン": "Parasimon",
    "パロットモン": "Parrotmon",
    "パタモン": "Patamon",
    "ポーンチェスモン (黒)": "Pawn Chessmon (Black)",
    "ポーンチェスモン （白）": "Pawn Chessmon (White)",
    "ポーンガオスモン": "Pawn Gaossmon",
    "ポーンシャウトモン": "Pawn Shoutmon",
    "ピーコックモン": "Peacockmon",
    "ペックモン": "Peckmon",
    "ペガスモン": "Pegasmon",
    "ペガスモン（X抗体）": "Pegasmon (X-Antibody)",
    "ペンモン": "Penmon",
    "ペタルドラモン": "Petaldramon",
    "ピーターモン": "Petermon",
    "プチメラモン": "Peti Meramon",
    "プチマモン": "Petit Mamon",
    "プチモン": "Petitmon",
    "ファラオモン": "Pharaohmon",
    "ファスコモン": "Phascomon",
    "フェレスモン": "Phelesmon",
    "ピッコロモン": "Piccolomon",
    "ピックモン": "Pickmon",
    "ピックモンズパチンコ": "Pickmons Slingshot",
    "ピコデビモン": "Pico Devimon",
    "ピッドモン": "Pidmon",
    "ピエモン": "Piemon",
    "パイルボルケーモン": "Pile Volcamon",
    "ピロモン": "Pillomon",
    "ピナモン": "Pinamon",
    "ピノッキモン": "Pinochimon",
    "ピピモン": "Pipimon",
    "ピピスモン": "Pipismon",
    "ピラニモン": "Piranimon",
    "ピストモン": "Pistmon",
    "ピチモン": "Pitchmon",
    "ピヨモン": "Piyomon",
    "プラチナヌメモン": "Platinum Numemon",
    "プラチナスカモン": "Platinum Scumon",
    "プレシオモン": "Plesiomon",
    "プレシオモン（X抗体）": "Plesiomon (X-Antibody)",
    "プロットモン": "Plotmon",
    "プロットモン（X抗体）": "Plotmon (X-Antibody)",
    "プルートモン": "Plutomon",
    "ボルトバウタモン (融合体)": "Plutomon (Fusion)",
    "プルトダモン": "Plutodumon",
    "ポコモン": "Pokomon",
    "ポーラーベアモン": "Polar Bearmon",
    "ポームモン": "Pomumon",
    "ポンチョモン": "Ponchomon",
    "ポポモン": "Popomon",
    "ポキュパモン": "Porcupamon",
    "ポロモン": "Poromon",
    "ポテモン": "Potamon",
    "ポヨモン": "Poyomon",
    "プレイリモン": "Prairiemon",
    "プリンスマメモン": "Prince Mamemon",
    "プリンスマメモン（X抗体）": "Prince Mamemon (X-Antibody)",
    "プリスティモン": "Pristimon",
    "プロガノモン": "Proganomon",
    "プロトギズモン": "Proto Gizmon",
    "プロキシマモン": "Proximamon",
    "サイケモン": "Psychemon",
    "プテラノモン": "Pteranomon",
    "プテラノモン（X抗体）": "Pteranomon (X-Antibody)",
    "プテロモン": "Pteromon",
    "パブリモン": "Publimon",
    "プッチーモン": "Pucchiemon",
    "プッチーモン（緑）": "Pucchiemon (Green)",
    "プカモン": "Pukamon",
    "プクモン": "Pukumon",
    "パルスモン": "Pulsemon",
    "パンプモン": "Pumpmon",
    "パンチナラビモン": "Punch Narabimon",
    "プニモン": "Punimon",
    "パンクモン": "Punkmon",
    "ププモン": "Pupumon",
    "プロロモン": "Puroromon",
    "プルルモン": "Pururumon",
    "プスモン": "Pusumon",
    "プスリモン": "Pusurimon",
    "プットモン": "Puttimon",
    "プワモン": "Puwamon",
    "プヨモン": "Puyomon",
    "プヨヨモン": "Puyoyomon",
    "ピョコモン": "Pyocomon",
    "ピョンモン": "Pyonmon",
    "ピョントモン": "Pyontomon",
    "ピラミディモン": "Pyramidimon",
    "チンロンモン": "Qinglongmon",
    "クオンタモン": "Quantumon",
    "クオーツモン": "Quartzmon",
    "クイーンチェスモン": "Queen Chessmon",
    "クイーンビーモン": "Queenbeemon",
    "ラフレシモン": "Rafflesimon",
    "ラグナロードモン": "Ragna Lordmon",
    "ラグナモン": "Ragnamon",
    "ラグエルモン": "Raguelmon",
    "ライデンモン": "Raidenmon",
    "ライヒモン": "Raihimon",
    "ライジルドモン": "Raiji Ludomon",
    "ライジンモン": "Raijinmon",
    "ランページグレイモン": "Rampage Greymon",
    "ラーナモン": "Ranamon",
    "ラピッドモン（X抗体）": "Rapidmon (X-Antibody)",
    "ラピッドモン": "Rapidmon Armor",
    "ラピッドモン": "Rapidmon Perfect",
    "ラプタースパロウモン": "Raptor Sparrowmon",
    "ラプタードラモン": "Raptordramon",
    "レアモン": "Raremon",
    "レアレアモン": "Rare Raremon",
    "レアスターソード": "Rare Star Sword",
    "ラセンモン": "Rasenmon",
    "ラセンモン：激昂モード": "Rasenmon: Fury Mode",
    "ラジエルモン": "Rasielmon",
    "レイヴモン": "Ravmon",
    "レイヴモン：バーストモード": "Ravmon: Burst Mode",
    "リベリモン": "Rebellimon",
    "レッドブイドラモン": "Red V-dramon",
    "レッドベジーモン": "Red Vegimon",
    "レガレクスマモン": "Regalecusmon",
    "レグルモン": "Regulumon",
    "レグルスモン": "Regulusmon",
    "レレモン": "Relemon",
    "レナモン": "Renamon",
    "レナモン（X抗体）": "Renamon (X-Antibody)",
    "レッパモン": "Reppamon",
    "レプティリモン": "Reptilimon",
    "リバース・ウェディンモン": "Reverse Weddinmon",
    "リボルモン": "Revolmon",
    "ランフォモン": "Rhamphomon",
    "ライノカブテリモン": "Rhino Kabuterimon",
    "ライノモン": "Rhinomon",
    "ライノモン（X抗体）": "Rhinomon (X-Antibody)",
    "リンクモン": "Rinkmon",
    "ライズグレイモン": "Rize Greymon",
    "ライズグレイモン（X抗体）": "Rize Greymon (X-Antibody)",
    "ルークチェスモン (黒)": "Rook Chessmon (Black)",
    "ルークチェスモン (白)": "Rook Chessmon (White)",
    "ロゼモン": "Rosemon",
    "ロゼモン（X抗体）": "Rosemon (X-Antibody)",
    "ロゼモン：バーストモード": "Rosemon: Burst Mode",
    "ルビウスドラモン": "Rubeusdramon",
    "ルカモン": "Rukamon",
    "ランナモン": "Runnermon",
    "ルリモン": "Rurimon",
    "ラストティラノモン": "Rust Tyranomon",
    "リュウダモン": "Ryudamon",
    "リュウグウモン": "Ryugumon",
    "サーベルレオモン": "Saber Leomon",
    "セーバードラモン": "Saberdramon",
    "サジタリモン": "Sagittarimon",
    "サゴモン": "Sagomon",
    "セントガルゴモン": "Saint Galgomon",
    "サクモン": "Sakumon",
    "サクラダモン": "Sakuradamon",
    "サクテキモニタモン": "Sakuteki Monitamon",
    "サクットモン": "Sakuttomon",
    "サクヤモン": "Sakuyamon",
    "サクヤモン：巫女モード": "Sakuyamon: Miko Mode",
    "サクヤモン（X抗体）": "Sakuyamon (X-Antibody)",
    "サラマンダモン": "Salamandamon",
    "サンドヤンマモン": "Sand Yanmamon",
    "サンティラモン": "Sandiramon",
    "サングルゥモン": "Sangloupmon",
    "サンゴモン": "Sangomon",
    "サンタアグモン": "Santa Agumon",
    "サンゾモン": "Sanzomon",
    "セイバーハックモン": "Savior Hackmon",
    "スコピオモン": "Scorpiomon",
    "スカッドミサイモン": "Scud Missimon",
    "スカモン": "Scumon",
    "シードラモン": "Seadramon",
    "シードラモン（X抗体）": "Seadramon (X-Antibody)",
    "シーホモン": "Seahomon",
    "シールズドラモン": "Sealsdramon",
    "サーチモン": "Searchmon",
    "セイテンゴクウモン": "Seiten Gokuwmon",
    "セッカモン": "Sekkamon",
    "セフィロトモン": "Sephirothmon",
    "セピックモン": "Sepikmon",
    "セラフィモン": "Seraphimon",
    "セトモン": "Sethmon",
    "セトモンワイルドモード": "Sethmon Wild Mode",
    "シェイドモン": "Shademon",
    "シェイドモン（ネネＶｅｒ.）": "Shademon (Nene Ver.)",
    "シェイドラモン": "Shadramon",
    "シャガラモン": "Shagaramon",
    "シャカモン": "Shakamon",
    "シャッコウモン": "Shakkoumon",
    "シャコモン": "Shakomon",
    "シャコモン（X抗体）": "Shakomon (X-Antibody)",
    "シャーマモン": "Shamamon",
    "シャークモン": "Sharkmon",
    "シャウジンモン": "Shawujinmon",
    "シープモン": "Sheepmon",
    "シェルモン": "Shellmon",
    "シマユニモン": "Shima Unimon",
    "しんもんざえモン": "Shin Monzaemon",
    "シャイングレイモン": "Shine Greymon",
    "シャイングレイモン ルインモード": "Shine Greymon: Ruin Mode",
    "シャイングレイモン：バーストモード": "Shine Greymon: Burst Mode",
    "シシマモン": "Shishimamon",
    "シーヴァモン": "Shivamon",
    "シューモン": "Shoemon",
    "シューシューモン": "Shoeshoemon",
    "シャニタモン": "Shonitamon",
    "シューティングスターモン": "Shooting Starmon",
    "シュートモン": "Shootmon",
    "ショートモン": "Shortmon",
    "シャウキュートモン": "ShouCutemon",
    "シャウトモン": "Shoutmon",
    "シャウトモン(キングVer.)": "Shoutmon (King Ver.)",
    "シャウトモン (黒)": "Shoutmon B",
    "シャウトモン (青)": "Shoutmon (Blue)",
    "シャウトモン (黄)": "Shoutmon Y",
    "シャウトモンＤＸ": "Shoutmon DX",
    "シャウトモンＥＸ６": "Shoutmon EX6",
    "シャウトモンＳＨ": "Shoutmon SH",
    "シャウトモンＸ１０": "Shoutmon X10",
    "シャウトモンＸ２": "Shoutmon X2",
    "シャウトモンＸ２ (不完全Ｘ４)": "Shoutmon X2 (Incomplete X4)",
    "シャウトモンＸ２ プラス Ｍ": "Shoutmon X2 Plus M",
    "シャウトモンＸ３": "Shoutmon X3",
    "シャウトモンＸ３ＧＭ": "Shoutmon X3GM",
    "シャウトモンＸ３ＳＤ": "Shoutmon X3SD",
    "シャウトモンＸ４": "Shoutmon X4",
    "シャウトモンＸ４Ｂ": "Shoutmon X4B",
    "シャウトモンＸ４Ｋ": "Shoutmon X4K",
    "シャウトモンＸ４Ｓ": "Shoutmon X4S",
    "シャウトモンＸ５": "Shoutmon X5",
    "シャウトモンＸ５＋スカルグレイモン": "Shoutmon X5 + Skull Greymon",
    "シャウトモンＸ５Ｂ": "Shoutmon X5B",
    "シャウトモンＸ５Ｓ": "Shoutmon X5S",
    "シャウトモンＸ６": "Shoutmon X6",
    "シャウトモンＸ７": "Shoutmon X7",
    "シャウトモンＸ７：スペリオルモード": "Shoutmon X7: Superior Mode",
    "シャウトモン＋ドルルキャノン": "Shoutmon + Dorulu Cannon",
    "シャウトモン＋ジェットスパロウ": "Shoutmon + Jet Sparrow",
    "シャウトモン＋スターソード": "Shoutmon + Star Sword",
    "シュラウドモン": "Shroudmon",
    "シュリモン": "Shurimon",
    "シューツモン": "Shutumon",
    "シーサモン": "Siesamon",
    "シーサモン（X抗体）": "Siesamon (X-Antibody)",
    "シルフィーモン": "Silphymon",
    "シンドゥーラモン": "Sinduramon",
    "セイレーンモン": "Sirenmon",
    "シリウスモン": "Siriusmon",
    "シスタモン・ブラン": "Sistermon Blanc",
    "シスタモン・ブラン（覚醒）": "Sistermon Blanc (Awake)",
    "シスタモン・シエル": "Sistermon Ciel",
    "シスタモン・シエル（覚醒）": "Sistermon Ciel (Awake)",
    "シスタモン・ノワール": "Sistermon Noir",
    "シスタモン・ノワール（覚醒）": "Sistermon Noir (Awake)",
    "スカーディモン": "Skadimon",
    "スカルバルキモン": "Skull Baluchimon",
    "スカルグレイモン": "Skull Greymon",
    "スカルグレイモン: \"G\" 侵食モード": "Skull Greymon: \"G\" Erosion Mode",
    "スカルナイトモン": "Skull Knightmon",
    "スカルナイトモン：アローモード": "Skull Knightmon: Arrow Mode",
    "スカルナイトモン：ビッグアックスモード": "Skull Knightmon: Big Axe Mode",
    "スカルナイトモン": "Skull Knightmon (Blue)",
    "スカルナイトモンBR": "Skull Knightmon BR",
    "スカルナイトモン：騎馬モード": "Skull Knightmon: Cavalier Mode",
    "スカルナイトモン：ナギナタモード": "Skull Knightmon: Naginata Mode",
    "スカルナイトモン": "Skull Knightmon (White)",
    "スカルマンモン": "Skull Mammon",
    "スカルマンモン（X抗体）": "Skull Mammon (X-Antibody)",
    "スカルサタモン": "Skull Satamon",
    "スカルシードラモン": "Skull Seadramon",
    "スラッシュエンジェモン": "Slash Angemon",
    "スレイヤードラモン": "Slayerdramon",
    "スレイプモン": "Sleipmon",
    "スレイプモン（X抗体）": "Sleipmon (X-Antibody)",
    "スナッチモン": "Snatchmon",
    "スナイモン": "Snimon",
    "スノーゴブリモン": "Snow Goburimon",
    "ソーラーモン": "Solarmon",
    "ソルガルモン": "Soloogarmon",
    "ソーサリモン": "Sorcerimon",
    "ソウルモン": "Soulmon",
    "サウンドバードモン": "Soundbirdmon",
    "スパーダモン": "Spadamon",
    "スパロウモン": "Sparrowmon",
    "スパロウモン（アフター バー ナー）": "Sparrowmon AB",
    "スピノモン": "Spinomon",
    "スプラッシュモン": "Splashmon",
    "スプラッシュモンダークネスモード": "Splashmon Darkness Mode (Drippins)",
    "スプラッシュモンダークネスモード": "Splashmon Darkness Mode",
    "スターモン": "Starmon",
    "スターモン（X抗体）": "Starmon (X-Antibody)",
    "スターモンズ": "Starmons",
    "スターアックス": "Star Axe",
    "ステゴモン": "Stegomon",
    "スティフィルモン": "Stiffilmon",
    "スティングモン": "Stingmon",
    "スティングモン": "Stingmon (Black)",
    "ストラビモン": "Strabimon",
    "ストライクドラモン": "Strikedramon",
    "スティラコモン": "Styracomon",
    "狻猊兽": "Suannishou",
    "サブマリモン": "Submarimon",
    "スイジンモン": "Suijinmon",
    "スナモン": "Sunamon",
    "スナリザモン": "Sunarizamon",
    "サンフラウモン": "Sunflowmon",
    "サンモン": "Sunmon",
    "スーパーダークナイトモン": "Super Dark Knightmon",
    "スーパースターモン": "Superstarmon",
    "サーフィモン": "Surfimon",
    "スサノオモン": "Susanoomon",
    "スワンモン": "Swanmon",
    "スイムモン": "Swimmon",
    "ジンバーアンゴラモン": "Symbare Angoramon",
    "タクティモン": "Tactimon",
    "テイルモン": "Tailmon",
    "テイルモン（X抗体）": "Tailmon (X-Antibody)",
    "ターキモン": "Takinmon",
    "タクトウモン": "Takutoumon",
    "タクトウモン：ラースモード": "Takutoumon: Wrath Mode",
    "タネモン": "Tanemon",
    "タンクドラモン": "Tankdramon",
    "タンクモン": "Tankmon",
    "タオモン": "Taomon",
    "タオモン(銀)": "Taomon (Silver)",
    "タオティエモン": "Taotiemon",
    "ターゲットモン": "Targetmon",
    "テクノドラモン": "Technodramon",
    "テッカモン": "Tekkamon",
    "テンポモン": "Tempomon",
    "テングモン": "Tengumon",
    "テンコモン": "Tenkomon",
    "テントモン": "Tentomon",
    "テリアモン": "Terriermon",
    "テリアモン（X抗体）": "Terriermon (X-Antibody)",
    "テリアモン助手": "Terriermon Assistant",
    "テスラジェリーモン": "Tesla Jellymon",
    "テティスモン": "Thetismon",
    "サンダーボールモン": "Thunderballmon",
    "サンダーボールモン（X抗体）": "Thunderballmon (X-Antibody)",
    "サンダーバーモン": "Thunderbirmon",
    "ティアルドモン": "Tia Ludomon",
    "タイガーヴェスパモン": "Tiger Vespamon",
    "ティンカーモン": "Tinkermon",
    "タイタモン": "Titamon",
    "タイタモン＋スカルバルキモン": "Titamon + Skull Baluchimon",
    "トラロックモン": "Tlalocmon",
    "トビウモン": "Tobiumon",
    "トブキャットモン": "Tobucatmon",
    "トーカンモン": "Tocanmon",
    "トゲモグモン": "Togemogumon",
    "トゲモン": "Togemon",
    "トゲモン（X抗体）": "Togemon (X-Antibody)",
    "トコモン": "Tokomon",
    "トコモン（X抗体）": "Tokomon (X-Antibody)",
    "トモリモン": "Tomorimon",
    "トノサマゲコモン": "Tonosama Gekomon",
    "トノサママメモン": "Tonosama Mamemon",
    "とりからボールモン": "Torikara Ballmon",
    "トロピアモン": "Toropiamon",
    "トータモン": "Tortamon",
    "トイアグモン": "Toy Agumon",
    "トイアグモン（黒）": "Toy Agumon (Black)",
    "トレイルモン アングラー": "Trailmon Angler",
    "トレイルモン ボール": "Trailmon Ball",
    "トレイルモン戦闘フォーム": "Trailmon Battle Form",
    "トレイルモン バッファロー": "Trailmon Buffalo",
    "トレイルモン Ｃ－８９型": "Trailmon C-89",
    "トレイルモン フランケン": "Trailmon Franken",
    "トレイルモン ケトル": "Trailmon Kettle",
    "トレイルモン モール": "Trailmon Mole",
    "トレイルモン ラクーンドッグ": "Trailmon Raccoon Dog",
    "トレイルモン ワーム": "Trailmon Worm",
    "闇のトレイルモン": "Trailmon of Darkness",
    "トリケラモン": "Triceramon",
    "トリケラモン（X抗体）": "Triceramon (X-Antibody)",
    "トループモン": "Troopmon",
    "ツブモン": "Tsubumon",
    "ツメモン": "Tsumemon",
    "ツチダルモン": "Tuchidarumon",
    "ツカイモン": "Tukaimon",
    "ツノモン": "Tunomon",
    "ターボモン": "Turbomon",
    "トゥルイエモン": "Turuiemon",
    "タスクモン": "Tuskmon",
    "ツワーモン": "Tuwarmon",
    "チィリンモン": "Tyilinmon",
    "ティロモン": "Tylomon",
    "ティロモン（X抗体）": "Tylomon (X-Antibody)",
    "ティラノモン": "Tyranomon",
    "ティラノモン（X抗体）": "Tyranomon (X-Antibody)",
    "タイラントカブテリモン": "Tyrant Kabuterimon",
    "チューモン": "Tyumon",
    "チューチューモン": "Tyutyumon",
    "ウッコモン": "Ukkomon",
    "アルフォースブイドラモン": "Ulforce V-dramon",
    "アルフォースブイドラモンフューチャーモード": "Ulforce V-dramon Future Mode",
    "アルフォースブイドラモン（X抗体）": "Ulforce V-dramon (X-Antibody)",
    "アルティメットブラキモン": "Ultimate Brachimon",
    "アルティメットカオスモン": "Ultimate Chaosmon",
    "ウモン": "Umon",
    "ユニモン": "Unimon",
    "トレイルモン": "Unnamed Trailmon 1 (Next)",
    "トレイルモン": "Unnamed Trailmon 2 (Next)",
    "トレイルモン": "Unnamed Trailmon 3 (Next)",
    "ウパモン": "Upamon",
    "ウラシマモン": "Urashimamon",
    "ブイドラモン": "V-dramon",
    "ブイドラモン(黒)": "V-dramon (Black)",
    "ブイモン": "V-mon",
    "ベーダモン": "Vademon",
    "ベーダモン（X抗体）": "Vademon (X-Antibody)",
    "ヴァジラモン": "Vajramon",
    "ヴァロドゥルモン": "Valdurmon",
    "ヴァルキリモン": "Valkyrimon",
    "バルブモン": "Valvemon",
    "ヴァンデモン": "Vamdemon",
    "ヴァンデモン（X抗体）": "Vamdemon (X-Antibody)",
    "ベジーモン": "Vegimon",
    "ベルグモン": "Velgrmon",
    "ヴェノムヴァンデモン": "Venom Vamdemon",
    "ヴェノムヴァンデモンアンデッド": "Venom Vamdemon Undead",
    "ヴェヌスモン": "Venusmon",
    "ヴァーミリモン": "Vermillimon",
    "ヴェスパモン": "Vespamon",
    "ビクトリーグレイモン": "Victory Greymon",
    "ヴィカラーラモン": "Vikaralamon",
    "ヴァイクモン": "Vikemon",
    "ボルケーモン": "Volcamon",
    "ヴォルケニックドラモン": "Volcanicdramon",
    "ヴォルクドラモン": "Volcdramon",
    "ボルトバウタモン": "Voltobautamon",
    "ボルトバウタモン (融合体)": "Voltobautamon (Fusion)",
    "ヴォルテクスドラモン": "Vortexdramon",
    "ヴォーボモン": "Vorvomon",
    "ヴリトラモン": "Vritramon",
    "ウルカヌスモン": "Vulcanusmon",
    "バルチャモン": "Vulturemon",
    "ワンコモン": "Wankomon",
    "ワニャモン": "Wanyamon",
    "ウォーグレイモン": "War Greymon",
    "ウォーグレイモン（X抗体）": "War Greymon (X-Antibody)",
    "ウォーグレイモン: \"G\" 侵食モード": "War Greymon: \"G\" Erosion Mode",
    "ワルもんざえモン": "Waru Monzaemon",
    "ワルシードラモン": "Waru Seadramon",
    "ワスプモン": "Waspmon",
    "ウェディンモン": "Weddinmon",
    "ウェンディモン": "Wendimon",
    "ワーガルルモン": "Were Garurumon",
    "ワーガルルモン（X抗体）": "Were Garurumon (X-Antibody)",
    "ワーガルルモン黒": "Were Garurumon (Black)",
    "ワーガルルモン：サジタリウスモード": "Were Garurumon: Sagittarius Mode",
    "ウェズンガンマモン": "Wezen Gammamon",
    "ホエーモン": "Whamon",
    "ホエーモン完全体": "Whamon Perfect",
    "白いロップモン": "White Lopmon",
    "ウイングドラモン": "Wingdramon",
    "ワイズモン": "Wisemon",
    "ウィッチモン": "Witchmon",
    "ウィザーモン": "Wizarmon",
    "ウィザーモン（X抗体）": "Wizarmon (X-Antibody)",
    "ヴォルフモン": "Wolfmon",
    "ウルヴァモン": "Wolvermon",
    "ウッドモン": "Woodmon",
    "ウッドウッディモン": "Woodwoodymon",
    "ワームモン": "Wormmon",
    "シャンポンモン": "Xiangpengmon",
    "シャオモン": "Xiaomon",
    "シンテンモン": "Xingtianmon",
    "シーチューモン": "Xiquemon",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Astamon)",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Blossomon)",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Dobermon)",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Giga Breakdramon)",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Metal Tyranomon)",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Orgemon)",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Sagomon)",
    "クロスアップ アレスタードラモン": "Xros Up Arresterdramon (Sparrowmon)",
    "クロスアップ アスタモン": "Xros Up Astamon (Cerberumon)",
    "クロスアップ アスタモン": "Xros Up Astamon (Triceramon)",
    "クロスアップ バリスタモン": "Xros Up Ballistamon (Revolmon)",
    "クロスアップ ドルルモン": "Xros Up Dorulumon (Pawn Chessmon (White))",
    "クロスアップ ガムドラモン": "Xros Up Gumdramon (Kotemon)",
    "クロスアップ メルヴァモン": "Xros Up Mervamon (Beelzebumon)",
    "クロスアップ オメガシャウトモン": "Xros Up Omega Shoutmon (Dorulumon)",
    "クロスアップ オポッサモン": "Xros Up Opossummon (Candmon)",
    "クロスアップ シャウトモン": "Xros Up Shoutmon (Chibi Kamemon)",
    "クロスアップ シャウトモン": "Xros Up Shoutmon (Pinochimon)",
    "クロスアップ サブマリモン": "Xros Up Submarimon (Plesiomon)",
    "クロスアップ ツワーモン": "Xros Up Tuwarmon (Superstarmon)",
    "シェンウーモン": "Xuanwumon",
    "エクスブイモン": "XV-mon",
    "エクスブイモン(黒)": "XV-mon (Black)",
    "イエーガードルルモン": "Yaeger Dorulumon",
    "ヤキイモン": "Yakiimon",
    "ヤシャモン": "Yaksamon",
    "ヤンマモン": "Yanmamon",
    "ヤーモン": "Yarmon",
    "ヤタガラモン": "Yatagaramon",
    "ヤタガラモン（２００６アニメ版）": "Yatagaramon (2006 Anime Version)",
    "イーフーモン": "Yihumon",
    "ヨッ！ヨッ！モン": "Yo!Yo!mon",
    "ヨークモン": "Yolkmon",
    "ヨウコモン": "Youkomon",
    "ユキアグモン": "Yuki Agumon",
    "ユキアグモン": "Yuki Agumon (2006 Anime Version)",
    "ユキダルモン": "Yukidarumon",
    "ユキミボタモン": "Yukimi Botamon",
    "ユキナモン": "Yukinamon",
    "ユラモン": "Yuramon",
    "ズィードガルルモン": "Z'd Garurumon",
    "ザミエールモン": "Zamielmon",
    "ザンバモン": "Zanbamon",
    "ザンメツモン": "Zanmetsumon",
    "ザッソーモン": "Zassoumon",
    "ズィードミレニアモン": "Zeed Millenniumon",
    "ジークグレイモン": "Zeke Greymon",
    "ゼニモン": "Zenimon",
    "ゼファーガモン": "Zephagamon",
    "ゼリモン": "Zerimon",
    "朱鹮兽": "Zhuhuanshou",
    "スーツェーモン": "Zhuqiaomon",
    "ジンオウガルルモン": "Zino Garurumon",
    "ゾンビプルートモン": "Zombie Plutomon",
    "ゾンビモン": "Zombiemon",
    "ズバイガーモン": "Zubaeagermon",
    "ズバモン": "Zubamon",
    "ズドモン": "Zudomon",
    "ズルモン": "Zurumon",
    "オンモン": "Onmon"
}


/** ONE PIECE NAMES */
const onepiece_names = {
    "クリーク":"Krieg",
    "ルーシー":"Lucy",
    "アルビダ":"Alvida",
    "海ネコ":"Sea Cat",
    "カバジ":"Cabaji",
    "キャベンディッシュ":"Cavendish",
    "ギン":"Gin",
    "コビー":"Koby",
    "ネズミ":"Nezumi",
    "パール":"Pearl",
    "バギー":"Buggy",
    "ハサミ":"Pincers",
    "バルトロメオ":"Bartolomeo",
    "ヒグマ":"Higuma",
    "フルボディ":"Fullbody",
    "モーガン":"Morgan",
    "モージ":"Mohji",
    "バリア突進牛":"Barrier Bulls",
    "火拳":"Fire Fist",
    "見てろよ!エース!!!":"Just Watch Me, Ace!!!",
    "ブルック":"Brook",
    "アーロン":"Arlong",
    "ウソップ":"Usopp",
    "クロ":"Kuro",
    "ジャンゴ":"Jango",
    "ジュラキュール・ミホーク":"Dracule Mihawk",
    "ニャーバン兄弟":"Meowban Brothers",
    "バーソロミュー・くま":"Bartholomew Kuma",
    "ヒョウゾウ":"Hyouzou",
    "プリンプリン":"Purinpurin",
    "ホーディ・ジョーンズ":"Hody Jones",
    "ヨーキ":"Yorki",
    "ラブーン":"Laboon",
    "リューマ":"Ryuma",
    "強ェ弱ェは結果が決めるのさ":"The Outcome Will Tell Us Who's Strong and Who's Weak",
    "命令してるんだ 誰もおれに逆らうな!!!":"It's an Order! Do Not Defy Me!!!",
    "レベッカ":"Rebecca",
    "ヴィオラ":"Viola",
    "オオロンブス":"Orlumbus",
    "キュロス":"Kyros",
    "ケリー・ファンク":"Kelly Funk",
    "コアラ":"Koala",
    "サイ":"Sai",
    "サボ":"Sabo",
    "サンジ":"Sanji",
    "チンジャオ":"Chinjao",
    "ハイルディン":"Hajrudin",
    "ボビー・ファンク":"Bobby Funk",
    "モンキー・Ｄ・ルフィ":"Monkey.D.Luffy",
    "レオ":"Leo",
    "誰にも渡さねェよ!“あいつ”の形見だ":"And No One Else Can Have It! It's Our Memento of Him",
    "使ってけれ‼ルフィ先輩ィ!!!":"Go Ahead and Use 'Em, Mr. Luffy!!!",
    "“メラメラの実”はおれが食っていいか？":"Would You Let Me Eat the Flame-Flame Fruit?",
    "ドレスローザ王国":"Dressrosa Kingdom",
    "エネル":"Enel",
    "アマゾン":"Amazon",
    "オーム":"Ohm",
    "キャプテン・シーマーズ":"Captain Seamars",
    "ゲダツ":"Gedatsu",
    "コトリ":"Kotori",
    "ゴロー":"Goro",
    "サトリ":"Satori",
    "シュラ":"Shura",
    "神兵":"Heavenly Warriors",
    "ノラ":"Nola",
    "フザ":"Fuza",
    "ホーリー":"Holly",
    "ホトリ":"Hotori",
    "ヤマ":"Yama",
    "放電":"Varie",
    "神の裁き":"El Thor",
    "雷獣":"Lightning Beast Kiten",
    "雷龍":"Lightning Dragon",
    "万雷":"Mamaragan",
    "アブサロム":"Absalom",
    "オーズ":"Oars",
    "シャーロット・ローラ":"Charlotte Lola",
    "スポイル":"Spoil",
    "ドクトル・ホグバック":"Dr. Hogback",
    "トニートニー・チョッパー":"Tony Tony.Chopper",
    "ナミ":"Nami",
    "ニコ・ロビン":"Nico Robin",
    "パイレーツドッキング6":"Pirates Docking Six",
    "フランキー":"Franky",
    "ペローナ":"Perona",
    "マルガリータ":"Margarita",
    "リスキー兄弟":"The Risky Brothers",
    "ロロノア・ゾロ":"Roronoa Zoro",
    "ゴムゴムの暴風雨":"Gum-Gum Storm",
    "飛燕ボンナバン":"Swallow Bond en Avant",
    "人として恥ずかしいわ":"I Find It Embarrassing as a Human Being",
    "ウルージ":"Urouge",
    "カマキリ":"Kamakiri",
    "カルガラ":"Kalgara",
    "ガン・フォール":"Gan.Fall",
    "ゲンボウ":"Genbo",
    "コニス":"Conis",
    "ジュエリー・ボニー":"Jewelry Bonney",
    "タコバルーン":"Octoballoon",
    "ブラハム":"Braham",
    "モンブラン・ノーランド":"Mont Blanc Noland",
    "ラキ":"Raki",
    "ワイパー":"Wyper",
    "衝撃貝":"Impact Dial",
    "ゴムゴムの黄金回転弾":"Gum-Gum Golden Rifle",
    "へそ!!":"Heso!!",
    "ボア・ハンコック":"Boa Hancock",
    "トラファルガー・ロー":"Trafalgar Law",
    "エドワード・ニューゲート":"Edward Newgate",
    "スクラッチメン・アプー":"Scratchmen Apoo",
    "山さん":"Mountain God",
    "しらほし":"Shirahoshi",
    "Mr.2・ボン・クレー(ベンサム)":"Mr.2.Bon.Kurei(Bentham)",
    "キラー":"Killer",
    "カーリー・ダダン":"Curly.Dadan",
    "カヤ":"Kaya",
    "ノジコ":"Nojiko",
    "イデオ":"Ideo",
    "エンポリオ・イワンコフ":"Emporio.Ivankov",
    "ドンキホーテ・ロシナンテ":"Donquixote Rosinante",
    "モネ":"Monet",
    "メイナード":"Maynard",
    "シャンクス":"Shanks",
    "ギオン":"Gion",
    "シャーロット・プリン":"Charlotte Pudding",
    "センゴク":"Sengoku",
    "ヴィンスモーク・ソラ":"Vinsmoke Sora",
    "シキ":"Shiki",
    "人斬り鎌ぞう":"Hitokiri Kamazo",
    "光月モモの助":"Kouzuki Momonosuke",
    "モーダ":"Moda",
    "モンキー・D・ドラゴン":"Monkey.D.Dragon",
    "モンキー・D・ガープ":"Monkey.D.Garp",
    "モンキー・Ｄ・ガープ":"Monkey.D.Garp",
    "バジル・ホーキンス":"Basil Hawkins",
    "クロコダイル":"Crocodile",
    "ポートガス・D・エース":"Portgas.D.Ace",
    "ポートガス・Ｄ・エース":"Portgas.D.Ace",
    "キャロット":"Carrot",
    "ブラックマリア":"Black Maria",
    "シルバーズ･レイリー":"Silvers Rayleigh",
    "ウタ":"Uta",
    "ベン・ベックマン":"Benn.Beckman",
    "ライムジュース":"Limejuice",
    "Mr.3(ギャルディーノ)":"Mr.3(Galdino)",
    "カタリーナ・デボン":"Catarina Devon",
    "ジーザス・バージェス":"Jesus Burgess",
    "マーシャル・Ｄ・ティーチ":"Marshall.D.Teach",
    "たしぎ":"Tashigi",
    "ユースタス・キッド":"Eustass\"Captain\"Kid",
    "X・ドレーク":"X.Drake",
    "ジンベエ":"Jinbe",
    "アディオ":"Adio",
    "リム":"Lim",
    "ラッキー・ルウ":"Lucky.Roux",
    "マルコ":"Marco",
    "ドンキホーテ・ドフラミンゴ":"Donquixote Doflamingo",
    "ゲッコー・モリア":"Gecko Moria",
    "シリュウ":"Shiryu",
    "お玉":"Otama",
    "ヒナ":"Hina",
    "シャチ＆ペンギン":"Shachi & Penguin",
    "エドワード・ニューゲート":"Edward.Newgate",
    "シャーロット・カタクリ":"Charlotte Katakuri",
    "ウソ八":"Uso-Hachi",
    "おナミ":"O-Nami",
    "サン五郎":"San-Gorou",
    "シャーロット・ブリュレ":"Charlotte Brulee",

}
